name: PowderLux
favicon: null
layout_spectrum: 0.5931394258514047
typography_spectrum: 0.24720857525244355
title: When only the best will do
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.39061898179352283
  lightness: 0.6807269523851573
  saturation: 0.9986263965256512
  rhythmicContrast: 0.81681890017353
purpose: []
